### ISSUE TITLE
Broken / unfunctional

### ISSUE THREAD

**Issue by kranercc** [gregbakerstl/ssh_password_sniffer#1]
Username sniffing doesn't work neither does the password

**Comment by Greg-2600** [comment]
What operating system and openssh server version are you testing against?

**Comment by kranercc** [comment]
ubuntu 18.04 latest openssh server

**Comment by Greg-2600** [comment]
That was exactly my test bed, great.  

Let's talk password extraction first.  Did you allow for the 4096 byte sed buffer to fill?  This could take 10+ login attempts before you start seeing output.

**Comment by Greg-2600** [comment]
Closing - unable to reproduce.  Please let me know if you still have an issue after waiting for buffer to fill.

**Comment by kranercc** [comment]
It is still not showing output even after a bruteforce with 100 login attempts

**Comment by Greg-2600** [comment]
reopened.

**Comment by Greg-2600** [comment]
please confirm you have `strace` installed - this should be a feature of this program anyway.

**Comment by Greg-2600** [comment]
When you run this command, do you get a PID that belongs to the SSHd parent process?:

`ps aux|grep "sshd -D"|grep -v grep|awk {'print $2'}`

If not, that's the bug - and is related to portability.  I was incorrect about Ubuntu being my test bed - this was developed on a raspberry pi.

If so, let's see if strace is giving you output at all.
Use the pid of your parent SSHd process, and try attaching strace to it: 

`strace -e trace=read -e read=6 -f -p {SSH PID}`

**Comment by kranercc** [comment]
jesus christ, i told you i have everything installed, your script doesn't show any even after a bruteforce attack on it, just delete it permanetly from github and stop trying to make yourself look good, your script is abysmal

**Comment by Greg-2600** [comment]
LOL

**Comment by Greg-2600** [comment]
I could not have asked for a better first issue.  Hopefully this guy doesn't yell at his mom when whining about another hot pocket.
